TRG_MODULES = [
    "image_encoder.blocks.0.attn.qkv",
    "image_encoder.blocks.1.attn.qkv",
    "image_encoder.blocks.2.attn.qkv",
    "image_encoder.blocks.3.attn.qkv",
    "image_encoder.blocks.4.attn.qkv",
    "image_encoder.blocks.5.attn.qkv",
    "image_encoder.blocks.6.attn.qkv",
    "image_encoder.blocks.7.attn.qkv",
    "image_encoder.blocks.8.attn.qkv",
    "image_encoder.blocks.9.attn.qkv",
    "image_encoder.blocks.10.attn.qkv",
    "image_encoder.blocks.11.attn.qkv",
    # Mask Decoder
    "mask_decoder.transformer.layers.0.self_attn.q_proj",
    # "mask_decoder.transformer.layers.0.self_attn.k_proj",
    "mask_decoder.transformer.layers.0.self_attn.v_proj",
    'mask_decoder.transformer.layers.0.cross_attn_token_to_image.q_proj',
    # 'mask_decoder.transformer.layers.0.cross_attn_token_to_image.k_proj',
    'mask_decoder.transformer.layers.0.cross_attn_token_to_image.v_proj',
    'mask_decoder.transformer.layers.0.cross_attn_image_to_token.q_proj',
    # 'mask_decoder.transformer.layers.0.cross_attn_image_to_token.k_proj',
    'mask_decoder.transformer.layers.0.cross_attn_image_to_token.v_proj',
    'mask_decoder.transformer.layers.1.self_attn.q_proj',
    # 'mask_decoder.transformer.layers.1.self_attn.k_proj',
    'mask_decoder.transformer.layers.1.self_attn.v_proj',
    'mask_decoder.transformer.layers.1.cross_attn_token_to_image.q_proj',
    # 'mask_decoder.transformer.layers.1.cross_attn_token_to_image.k_proj',
    'mask_decoder.transformer.layers.1.cross_attn_token_to_image.v_proj',
    'mask_decoder.transformer.layers.1.cross_attn_image_to_token.q_proj',
    # 'mask_decoder.transformer.layers.1.cross_attn_image_to_token.k_proj',
    'mask_decoder.transformer.layers.1.cross_attn_image_to_token.v_proj',
    'mask_decoder.transformer.final_attn_token_to_image.q_proj',
    # 'mask_decoder.transformer.final_attn_token_to_image.k_proj',
    'mask_decoder.transformer.final_attn_token_to_image.v_proj'
]